FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend/
COPY manage.py ./

COPY volunteermatch/ ./volunteermatch/

RUN python manage.py migrate

RUN python manage.py seed_db

RUN python manage.py seed_db

RUN python manage.py collectstatic --noinput

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "volunteermatch.asgi:application"]
