# Generated by Django 5.1.6 on 2025-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_volunteer_public_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dates_worked',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
