# Generated by Django 5.1.6 on 2025-05-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_application_dates_worked'),
        ('backend', '0012_organizationotp'),
    ]

    operations = [
    ]
